name: Pull request

on:
  pull_request:

jobs:
  verify-and-scan-bullseye:
    permissions:
      security-events: write  
    uses: ./.github/workflows/jobs/wf_verifyandscan.yaml
    with:
      rootfs_version: "bullseye"
      dockerfile: "Dockerfile.11"
  verify-and-scan-bookworm:
    permissions:
      security-events: write  
    uses: ./.github/workflows/jobs/wf_verifyandscan.yaml
    with:
      rootfs_version: "bookworm"
      dockerfile: "Dockerfile.12"
