name: Pull request

on:
  pull_request:

env:
  DEFAULT_ROOTFS_VERSION: bullseye

jobs:
  verify-and-scan:
    permissions:
      security-events: write  
    uses: ./.github/workflows/wf_verifyandscan.yaml
    with:
      rootfs_version: ${{ env.$DEFAULT_ROOTFS_VERSION }}
