name: Push to main line
on:
  push:
    branches:
      - main

jobs:
  build-and-push-bookworm:
    secrets: inherit
    uses: ./.github/workflows/wf_buildandpush.yaml
    with:
      rootfs_version: "bookworm"
      tags: "groundhog2k/distroless-base-image:12, groundhog2k/distroless-base-image:bookworm"
