name: Push to main line
on:
  push:
    branches:
      - main

jobs:
  build-and-push-bullseye:
    secrets: inherit
    uses: ./.github/workflows/wf_buildandpush.yaml
    with:
      rootfs_version: "bullseye"
      tags: "groundhog2k/distroless-base-image:11, groundhog2k/distroless-base-image:bullseye"
