name: Push to main line
on:
  push:
    branches:
      - main

jobs:
  build-and-push-bullseye:
    uses: ./.github/workflows/wf_buildandpush.yaml
    with:
      tags: "groundhog2k/distroless-base-image:11, groundhog2k/distroless-base-image:bullseye"
