name: Push to main line
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-and-push:
    uses: ./.github/workflows/wf_buildandpush.yaml
    with:
      tags: "groundhog2k/distroless-base-image:11, groundhog2k/distroless-base-image:bullseye"
