name: Scheduled image update
on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-and-push-bullseye:
    secrets: inherit
    uses: ./.github/workflows/wf_build-bullseye.yaml
  build-and-push-bookworm:
    secrets: inherit
    uses: ./.github/workflows/wf_build-bookworm.yaml
