on: [pull_request]

jobs:
  verify-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request
        uses: actions/checkout@master
      - name: Build a temporary image for verification
        run: docker build . -t groundhog2k/distroless-base-image:verify
      - uses: ./.github/workflows/trivy-scan.yaml
      - uses: ./.github/workflows/grype-scan.yaml
