name: Build and push Debian 12 based image
on:
  workflow_call:

jobs:
    build-and-push-bookworm:
      secrets: inherit
      uses: ./.github/workflows/wf_buildandpush.yaml
      with:
        rootfs_version: "bookworm"
        dockerfile: "Dockerfile.12"
        tags: "groundhog2k/distroless-base-image:12, groundhog2k/distroless-base-image:bookworm"
