name: Build and push Debian 11 based image
on:
  workflow_call:

jobs:
    build-and-push-bullseye:
      uses: ./.github/workflows/wf_buildandpush.yaml
      with:
        rootfs_version: "bullseye"
        dockerfile: "Dockerfile.11"
        tags: "groundhog2k/distroless-base-image:11, groundhog2k/distroless-base-image:bullseye"
